version: '3.8'

services:
  server:
    build: server
    container_name: server_container
    ports:
      - "9090:9090"

  gateway:
    build: gateway
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090